<?php

namespace Dive\PlatformBundle\Entity;

/**
 * AdherentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdherentsRepository extends \Doctrine\ORM\EntityRepository
{
}
