<?php

namespace Dive\PlatformBundle\Entity;

/**
 * CenterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CenterRepository extends \Doctrine\ORM\EntityRepository
{
}
