dive_platform:
    resource: "@DivePlatformBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:   /login
    defaults:  { _controller: DiveUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout